### ISSUE TITLE
HTTP 500 Error

### ISSUE THREAD

**Issue by Shackelford-Arden** [PenningDevelopment/openVM#2]
Hello!

Just tried installing this. After getting to the first form where it asks for the database information, I click __Get Started__ and then I get the error. All the information is correct as I had it when I created the user & DB.

Any thoughts? I checked the logs directory and it seems they're not being written to.

**Comment by Shackelford-Arden** [comment]
Aha! I was looking in the wrong places for logs. I went and checked the web server logs. It seems __php-mysql__ wasn't installed. Checking your documentation, it seems that it's not included in the list of packages required to run. 

After getting that installed, I got further. Now I'm getting the following:

`Connection failed: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution`

In the last field (Database host) I'm simply entering __localhost__.

**Comment by matthewalanpenning** [comment]
Hello Arden,
What Linux distribution are you running and what version of PHP are you using? Using localhost as the database host is correct.

**Comment by Shackelford-Arden** [comment]
@matthewalanpenning ,

I'm on Ubuntu 18.04 with PHP 7.2 installed.

```
vm@vm:~$ apt-cache policy php
php:
  Installed: 1:7.2+60ubuntu1
```

**Comment by matthewalanpenning** [comment]
@Shackelford-Arden ,
It may be an issue with the use of the file() function in PHP. It was being used to check to see if there was an update on the github repository. I commented out the code. Try doing a "sudo git pull" in the openVM directory and see if that fixes the issue.

**Comment by Shackelford-Arden** [comment]
That resolved the issue for me. I've got another thing I'm running into but might be better suited via another issue.
