### ISSUE TITLE
Cannot open connection to hypervisor

### ISSUE THREAD

**Issue by Shackelford-Arden** [PenningDevelopment/openVM#3]
Title contains the message. I'm receiving the following message now that I'm logged in:

```
Cannot open connection to hypervisor
```

I've confirmed that www-data is a member of the libvirtd group:

```
vm@vm:/var/www$ groups www-data
www-data : libvirtd
```

Is there something else I may have missed?

For reference:
Ubuntu 18.04

**Comment by matthewalanpenning** [comment]
@Shackelford-Arden 
I just setup a clean install of Ubuntu 18.04, ran through the setup steps and got an issue when trying to add www-data to libvirtd. It appears as the group has been changed. I added www-data to the libvirt group (no d) and restarted the machine. It is working. Let me know if you have any luck.

**Comment by Shackelford-Arden** [comment]
Soooo 

1) That was helpful. Thank you.
2) I accidently uncommented a line in qemu.conf which was causing libvirt to never start.... I'm going to go to my corner now and re-think my life haha.

**Comment by matthewalanpenning** [comment]
@Shackelford-Arden 
Glad you got it working. Just an FYI, you will need to create a storage pool first and start it before you can create a VM with a storage drive. I just opened up a feedback page at openvm.tech/feedback. I would like to hear your thoughts on the software after you get a chance to use it.
Thanks,
Matt
