### ISSUE TITLE
No Error given if VM fails to be created

### ISSUE THREAD

**Issue by Shackelford-Arden** [PenningDevelopment/openVM#5]
There is no visible error shown when the VM fails to create. Looking around, it did create the disk image assigned to the VM, but it never fully initiated the VM.

Also, I'd think if it's going to fail, we'd want to not have it create the disk image, but that's just my opinion.

**Comment by matthewalanpenning** [comment]
@Shackelford-Arden 
I made some changes to the pages/domain/domain-create.php page. I like your thinking on creating the hard drive after a successful creation of the new virtual machine. I made that change as well as alerting errors. Let me know if this helps.

**Comment by matthewalanpenning** [comment]
software now has error reports
