### ISSUE TITLE
Links from Website

### ISSUE THREAD

**Issue by andiweidl** [PenningDevelopment/openVM#9]
Hello,

I have a question: Are you still active in this project? 

The links on your website are broken again (https://vmdashboard.org/latest/vmdashboard.tar.gz)

Could you fix this again?

Thank you very much

**Comment by matthewalanpenning** [comment]
I created a release here on GitHub (https://github.com/VMDashboard/vmdashboard/releases/tag/v19.01.03) and updated the website instructions to point to the tarball to download and extract from there. Let me know if you have any troubles.
